#!/bin/sh

set -e

echo "" >> ${JIANMU_DSL_FILE_PATH}
cat ${JIANMU_DSL_FILE_PATH} | while IFS= read line
do
    echo -n "${line}\n" | sed 's/\"/\\\\\\"/g' >> /tmp/dsl_tmp.yml
done

TASK_DSL=`cat /tmp/dsl_tmp.yml`
REQ_DATA="{\"dsl\":\"${TASK_DSL}\"}"
SIGNATURE=`echo -n "${REQ_DATA}" | openssl dgst -sha1 -hmac "${JIANMU_HUB_API_SK}"`

sendReq(){
  status_code=`curl -s -o /tmp/res_tmp -w %{http_code} -D /tmp/location_tmp \
  --request POST $1 \
  --header "X-Access-Key: ${JIANMU_HUB_API_AK}" \
  --header "X-Signature: ${SIGNATURE#*= }" \
  --header 'Content-Type: application/json' \
  --data "${REQ_DATA}"`
  echo $status_code
}

status_code=`sendReq "${JIANMU_HUB_URL}/hub/upload/node_definitions/versions"`

# redirect
if test ${status_code} -eq '301' -o ${status_code} -eq '302'
then
    cat /tmp/location_tmp | while read line
    do
      if test "${line%: *}" == "Location"
      then
        URL="${line#*: }"
        URL=${URL%$'\r'}
        echo $URL
        status_code=`sendReq "$URL"`
        break
      fi
    done
fi

if test ${status_code} -eq '403'
then
    echo "请检查api key"
    exit 1
elif test ${status_code} -ne '200'
then
    cat /tmp/res_tmp
    exit 1
fi

echo "发布成功"
